package com.example.mealprepper

// Meals hardcoded from link provided in the specification: https://ddracopo.github.io/DOCUM/courses/5cosc023w/meals.txt

val sampleMeals = listOf(
    Meal(
        idMeal = "52947",
        strMeal = "Sweet and Sour Pork",
        strDrinkAlternate = null,
        strCategory = "Pork",
        strArea = "Chinese",
        strInstructions = "Preparation\n1. Crack the egg into a bowl. Separate the egg white and yolk.\n\nSweet and Sour Pork\n2. Slice the pork tenderloin into strips.\n\n3. Prepare the marinade using a pinch of salt, one teaspoon of starch, two teaspoons of light soy sauce, and an egg white.\n\n4. Marinade the pork strips for about 20 minutes.\n\n5. Put the remaining starch in a bowl. Add some water and vinegar to make a starchy sauce.\n\nSweet and Sour Pork\nCooking Instructions\n1. Pour the cooking oil into a wok and heat to 190°C (375°F). Add the marinated pork strips and fry them until they turn brown. Remove the cooked pork from the wok and place on a plate.\n\n2. Leave some oil in the wok. Put the tomato sauce and white sugar into the wok, and heat until the oil and sauce are fully combined.\n\n3. Add some water to the wok and thoroughly heat the sweet and sour sauce before adding the pork strips to it.\n\n4. Pour in the starchy sauce. Stir-fry all the ingredients until the pork and sauce are thoroughly mixed together.\n\n5. Serve on a plate and add some coriander for decoration.",
        strMealThumb = "https://www.themealdb.com/images/media/meals/1529442316.jpg",
        strTags = "Sweet",
        strYoutube = "https://www.youtube.com/watch?v=mdaBIhgEAMo",
        strIngredient1 = "Pork",
        strIngredient2 = "Egg",
        strIngredient3 = "Water",
        strIngredient4 = "Salt",
        strIngredient5 = "Sugar",
        strIngredient6 = "Soy Sauce",
        strIngredient7 = "Starch",
        strIngredient8 = "Tomato Puree",
        strIngredient9 = "Vinegar",
        strIngredient10 = "Coriander",
        strMeasure1 = "200g",
        strMeasure2 = "1",
        strMeasure3 = "Dash",
        strMeasure4 = "1/2 tsp",
        strMeasure5 = "1 tsp",
        strMeasure6 = "10g",
        strMeasure7 = "10g",
        strMeasure8 = "30g",
        strMeasure9 = "10g",
        strMeasure10 = "Dash",
        strSource = null,
        strImageSource = null,
        strCreativeCommonsConfirmed = null,
        dateModified = null
    ),
    Meal(
        idMeal = "52850",
        strMeal = "Chicken Marengo",
        strDrinkAlternate = null,
        strCategory = "Chicken",
        strArea = "French",
        strInstructions = "Heat the oil in a large flameproof casserole dish and stir-fry the mushrooms until they start to soften. Add the chicken legs and cook briefly on each side to colour them a little.\nPour in the passata, crumble in the stock cube and stir in the olives. Season with black pepper – you shouldn’t need salt. Cover and simmer for 40 mins until the chicken is tender. Sprinkle with parsley and serve with pasta and a salad, or mash and green veg, if you like.",
        strMealThumb = "https://www.themealdb.com/images/media/meals/qpxvuq1511798906.jpg",
        strTags = null,
        strYoutube = "https://www.youtube.com/watch?v=U33HYUr-0Fw",
        strIngredient1 = "Olive Oil",
        strIngredient2 = "Mushrooms",
        strIngredient3 = "Chicken Legs",
        strIngredient4 = "Passata",
        strIngredient5 = "Chicken Stock Cube",
        strIngredient6 = "Black Olives",
        strIngredient7 = "Parsley",
        strIngredient8 = null,
        strIngredient9 = null,
        strIngredient10 = null,
        strMeasure1 = "1 tbs",
        strMeasure2 = "300g",
        strMeasure3 = "4",
        strMeasure4 = "500g",
        strMeasure5 = "1",
        strMeasure6 = "100g",
        strMeasure7 = "Chopped",
        strMeasure8 = null,
        strMeasure9 = null,
        strMeasure10 = null,
        strSource = "https://www.bbcgoodfood.com/recipes/3146682/chicken-marengo",
        strImageSource = null,
        strCreativeCommonsConfirmed = null,
        dateModified = null
    ),
    Meal(
        idMeal = "52997",
        strMeal = "Beef Banh Mi Bowls with Sriracha Mayo, Carrot & Pickled Cucumber",
        strDrinkAlternate = null,
        strCategory = "Beef",
        strArea = "Vietnamese",
        strInstructions = "Add'l ingredients: mayonnaise, sriracha\n\n1\n\nPlace rice in a fine-mesh sieve and rinse until water runs clear. Add to a small pot with 1 cup water (2 cups for 4 servings) and a pinch of salt. Bring to a boil, then cover and reduce heat to low. Cook until rice is tender, 15 minutes. Keep covered off heat for at least 10 minutes or until ready to serve.\n\n2\n\nMeanwhile, wash and dry all produce. Peel and finely chop garlic. Zest and quarter lime (for 4 servings, zest 1 lime and quarter both). Trim and halve cucumber lengthwise; thinly slice crosswise into half-moons. Halve, peel, and medium dice onion. Trim, peel, and grate carrot.\n\n3\n\nIn a medium bowl, combine cucumber, juice from half the lime, 1/4 tsp sugar (1/2 tsp for 4 servings), and a pinch of salt. In a small bowl, combine mayonnaise, a pinch of garlic, a squeeze of lime juice, and as much sriracha as you’d like. Season with salt and pepper.\n\n4\n\nHeat a drizzle of oil in a large pan over medium-high heat. Add onion and cook, stirring, until softened, 4-5 minutes. Add beef, remaining garlic, and 2 tsp sugar (4 tsp for 4 servings). Cook, breaking up meat into pieces, until beef is browned and cooked through, 4-5 minutes. Stir in soy sauce. Turn off heat; taste and season with salt and pepper.\n\n5\n\nFluff rice with a fork; stir in lime zest and 1 TBSP butter. Divide rice between bowls. Arrange beef, grated carrot, and pickled cucumber on top. Top with a squeeze of lime juice. Drizzle with sriracha mayo.",
        strMealThumb = "https://www.themealdb.com/images/media/meals/z0ageb1583189517.jpg",
        strTags = null,
        strYoutube = "",
        strIngredient1 = "Rice",
        strIngredient2 = "Onion",
        strIngredient3 = "Lime",
        strIngredient4 = "Garlic Clove",
        strIngredient5 = "Cucumber",
        strIngredient6 = "Carrots",
        strIngredient7 = "Ground Beef",
        strIngredient8 = "Soy Sauce",
        strIngredient9 = "",
        strIngredient10 = null,
        strMeasure1 = "White",
        strMeasure2 = "1",
        strMeasure3 = "1",
        strMeasure4 = "3",
        strMeasure5 = "1",
        strMeasure6 = "3 oz",
        strMeasure7 = "1 lb",
        strMeasure8 = "2 oz",
        strMeasure9 = "",
        strMeasure10 = null,
        strSource = "",
        strImageSource = null,
        strCreativeCommonsConfirmed = null,
        dateModified = null
    ),
    Meal(
        idMeal = "52973",
        strMeal = "Leblebi Soup",
        strDrinkAlternate = null,
        strCategory = "Vegetarian",
        strArea = "Tunisian",
        strInstructions = "Heat the oil in a large pot. Add the onion and cook until translucent.\nDrain the soaked chickpeas and add them to the pot together with the vegetable stock. Bring to the boil, then reduce the heat and cover. Simmer for 30 minutes.\nIn the meantime toast the cumin in a small ungreased frying pan, then grind them in a mortar. Add the garlic and salt and pound to a fine paste.\nAdd the paste and the harissa to the soup and simmer until the chickpeas are tender, about 30 minutes.\nSeason to taste with salt, pepper and lemon juice and serve hot.",
        strMealThumb = "https://www.themealdb.com/images/media/meals/x2fw9e1560460636.jpg",
        strTags = "Soup",
        strYoutube = "https://www.youtube.com/watch?v=BgRifcCwinY",
        strIngredient1 = "Olive Oil",
        strIngredient2 = "Onion",
        strIngredient3 = "Chickpeas",
        strIngredient4 = "Vegetable Stock",
        strIngredient5 = "Cumin",
        strIngredient6 = "Garlic",
        strIngredient7 = "Salt",
        strIngredient8 = "Harissa Spice",
        strIngredient9 = "Pepper",
        strIngredient10 = "Lime",
        strMeasure1 = "2 tbs",
        strMeasure2 = "1 medium finely diced",
        strMeasure3 = "250g",
        strMeasure4 = "1.5L",
        strMeasure5 = "1 tsp",
        strMeasure6 = "5 cloves",
        strMeasure7 = "1/2 tsp",
        strMeasure8 = "1 tsp",
        strMeasure9 = "Pinch",
        strMeasure10 = "1/2",
        strSource = "http://allrecipes.co.uk/recipe/43419/leblebi--tunisian-chickpea-soup-.aspx",
        strImageSource = null,
        strCreativeCommonsConfirmed = null,
        dateModified = null
    )
)
